# Generated by Django 5.2.6 on 2025-09-03 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='datereg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='placelabel',
            name='description',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
