# Generated by Django 5.2.6 on 2025-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0002_alter_objects_datereg_alter_placelabel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='hasIt',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='isInPlace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='whoIsIt',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placelabel',
            name='isEmpty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placelabel',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
    ]
