# Generated by Django 5.2.6 on 2025-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0003_objects_hasit_objects_isinplace_objects_whoisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='whoIsIt',
            field=models.CharField(blank=True, default='Propio', max_length=100, null=True),
        ),
    ]
