# Generated by Django 5.2.6 on 2025-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0004_alter_objects_whoisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='whoIsIt',
            field=models.CharField(default='Propio', max_length=100, null=True),
        ),
    ]
