# Generated by Django 5.2.6 on 2025-09-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0007_objtype_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placelabel',
            unique_together={('user', 'name')},
        ),
        migrations.AlterField(
            model_name='objtype',
            name='typename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placelabel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placelabel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='placelabel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='objtype',
            unique_together={('user', 'typename')},
        ),
        migrations.RemoveField(
            model_name='placelabel',
            name='isEmpty',
        ),
        migrations.RemoveField(
            model_name='placelabel',
            name='isFull',
        ),
    ]
