# Generated by Django 5.2.6 on 2025-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0008_alter_placelabel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelabel',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
