# Generated by Django 5.2.6 on 2025-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0009_placelabel_pseudonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='hasIt',
            field=models.CharField(blank=True, default='Yo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='whoIsIt',
            field=models.CharField(default='Yo', max_length=100, null=True),
        ),
    ]
