# Generated by Django 5.2.6 on 2025-09-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0010_alter_objects_hasit_alter_objects_whoisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelabel',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BoxLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='placelabels.placelabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
