# Generated by Django 5.2.6 on 2025-09-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0011_alter_placelabel_pseudonym_boxlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placelabel',
            name='description',
        ),
        migrations.AddField(
            model_name='placelabel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placelabels.room'),
        ),
    ]
