# Generated by Django 5.2.6 on 2025-09-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0012_room_remove_placelabel_description_placelabel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='boxlabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placelabels.boxlabel'),
        ),
    ]
