# Generated by Django 5.2.6 on 2025-09-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0013_objects_boxlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelabel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placelabels.room'),
        ),
    ]
