# Generated by Django 5.2.6 on 2025-09-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0014_alter_placelabel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelabel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
