# Generated by Django 5.2.6 on 2025-09-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0016_room_user_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelabel',
            name='room',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='placelabels.room'),
            preserve_default=False,
        ),
    ]
