# Generated by Django 5.2.6 on 2025-09-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0017_alter_placelabel_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placelabel',
            unique_together=set(),
        ),
    ]
