# Generated by Django 5.2.6 on 2025-09-06 21:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0018_alter_placelabel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxlabel',
            unique_together={('user', 'place', 'name')},
        ),
    ]
