# Generated by Django 5.2.6 on 2025-09-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placelabels', '0019_alter_boxlabel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxlabel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='boxlabel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
